# Generated by Django 5.0.4 on 2024-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='productcarosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
